### PR TITLE
Logs API improvements

### PR DESCRIPTION
**Pull request by hearnadam**
This change is the first to target some of the issues with `Logs` described in https://github.com/getkyo/kyo/issues/148

First and most importantly, we need a mechanism to allow users to define a logging interface which is not necessarily coupled to slf4j. I created an 'Unsafe' pure API which can enable users to provide their own logging interface. We can also use this to prevent the need for the slf4j interfaces in Kyo JS.

Unresolved issues:

1. Should we expose the default `unsafe` instance?
2. Should we use local or implicit for logger instance injection? For Kyo internals, it seems to make sense that we should use an implicit...
3. Should we expose `*Enabled` functions in the unsafe API?

### CODE REVIEW

**Comment by fwbrasil** [comment]
Geazi mentioned https://github.com/outr/scribe in Discord. Maybe we could integrate with it instead?

> Should we expose the default unsafe instance?

Yes, Kyo normally offers unsafe APIs since they might be required for performance-sensitive code.

> Should we use local or implicit for logger instance injection? For Kyo internals, it seems to make sense that we should use an implicit...

Maybe we could use a `local` users can override like in `Clocks` and `Consoles`?

> Should we expose *Enabled functions in the unsafe API?

I think so, they might be needed for performance-sensitive code.

**Comment by hearnadam** [comment]
> Geazi mentioned https://github.com/outr/scribe in Discord. Maybe we could integrate with it instead?

I'm not especially concerned with what logging interface we choose. I expect many companies are still using slf4j/logback. Most importantly, we should expose an API in `KyoApp` trait to provide an unsafe logging interface. This should enable users to provide any logger they want.

**Comment by fwbrasil** [comment]
LGTM! Thanks :)

**Comment by hearnadam** [comment]
@fwbrasil can you provide guidance where we should use `PlatformSpecific` mixins? I think it's reasonable to assume `val unsafe` can be defined per platform.

Do you have an concern with internal components using the default `unsafe` instance instead of the user provided one?

Perhaps we need a mechanism like ZIO's `bootstrap` for default instance values.

**Pull request merged**
