### PR TITLE
fix(stats): Handle delta overflows in Counter and Countergauge 

### LINKED ISSUE #410: Stats: handle overflows
Kyo now has its own implementation of metrics introduced by https://github.com/getkyo/kyo/pull/409. As [pointed out](https://github.com/getkyo/kyo/pull/409#discussion_r1610859626) in the review, the implementation doesn't handle overflows when reporting deltas to exporters.

A solution for this issue must address this issue for both `Counter` and `CounterGauge`. I haven't implemented a solution for this problem yet but it seems we could detect the overflow and still infer the correct delta.

### PR DESCRIPTION
**Pull request by mobley-trent**
Closes #410 
/claim #410 

- Handles overflow while calculating the delta in `Counter` and `CounterGauge`

### CODE REVIEW

**Comment by mobley-trent** [comment]
@fwbrasil I think this takes care of the rollover

**Comment by hearnadam** [comment]
I think the issue was looking for a more holistic solution, but regardless tests will be necessary for this bounty claim.

**Comment by mobley-trent** [comment]
Working on a better solution + tests

**Comment by mobley-trent** [comment]
Hi @fwbrasil @hearnadam this solution addresses the overflow on `last` by rolling over the remainder of the value to start from zero. This would mitigate the inaccuracies when dealing with negative numbers. Kindly review and advise if this was not the intended behaviour

**Comment by mobley-trent** [comment]
@fwbrasil @hearnadam I would appreciate your feedback

**Comment by fwbrasil** [comment]
Thank you! Sorry for the delay to review @mobley-trent

**Pull request merged**
