### PR TITLE
[core] include Abort[Nothing] in Async

### PR DESCRIPTION
**Pull request by fwbrasil**
`Async` already handles `Abort[Nothing]` but the effect wasn't included in the type intersection.

### CODE REVIEW

**Review by sideeffffect — COMMENTED** [review]
`Abort[Nothing]` corresponds to a fatal, unexpected failure/defect/bug, right?

In that case, shouldn't it already be subsumed by `IO` itself?

**Review by hearnadam — APPROVED** [review]

**Comment by hearnadam** [comment]
@fwbrasil after checking the build, it looks like this is breaking.

**Comment by fwbrasil** [comment]
> `Abort[Nothing]` corresponds to a fatal, unexpected failure/defect/bug, right?

Yes, it represents a `Result.Panic`. 

> In that case, shouldn't it already be subsumed by `IO` itself?

That's a good point. It seems it'd be more convenient but then `IO.Unsafe.run` will need to return a `Result`. Do you mind creating an issue for it so we can follow up separately? It'll be trickier to implement since `IO` doesn't handle `Abort` currently.

**Comment by fwbrasil** [comment]
Build should be fixed now. I hadn't realized that the `Reducible` evidences aren't necessary anymore since `Abort[Nothing]` is included in `Async`.

**Comment by sideeffffect** [comment]
created the new issues for this
* https://github.com/getkyo/kyo/issues/836

**Pull request merged**
