### PR TITLE
scala-js: add java-time dependency

### PR DESCRIPTION
**Pull request by hearnadam**
@johnhungerford can you try the snapshot and see if `zikyo` correctly builds?

### CODE REVIEW

**Comment by johnhungerford** [comment]
@hearnadam Is it published? I don't see any successful publish actions

**Comment by fwbrasil** [comment]
The build is failing with an error related to `EnableReflectiveInstantiation`. I was getting this error locally some time ago as well:

```
[error] -- Error: /home/runner/work/kyo/kyo/kyo-test/shared/src/main/scala/kyo/test/KyoSpecAbstract.scala:12:42 
[error] 12 |abstract class KyoSpecAbstract[S] extends ZIOSpecAbstract:
[error]    |                                          ^
[error]    |Toplevel definition EnableReflectiveInstantiation is defined in
[error]    |  /home/runner/.cache/coursier/v1/https/repo1.maven.org/maven2/org/portable-scala/portable-scala-reflect_sjs1_2.13/1.1.2/portable-scala-reflect_sjs1_2.13-1.1.2.jar(org/portablescala/reflect/annotation/package.class)
[error]    |and also in
[error]    |  /home/runner/.cache/coursier/v1/https/repo1.maven.org/maven2/org/portable-scala/portable-scala-reflect_2.13/1.1.2/portable-scala-reflect_2.13-1.1.2.jar(org/portablescala/reflect/annotation/EnableReflectiveInstantiation.class)
[error]    |One of these files should be removed from the classpath.
```

@hearnadam could we create our own constants instead? I think it'd be ideal to avoid the dependency.

**Comment by hearnadam** [comment]
I don't have time to create a replacement for the ZIOSpecAbstract, but we could consider just publishing it for jvm in the short term. How does that sound @fwbrasil ?

**Comment by fwbrasil** [comment]
Isn't the issue only with those constants? Do you foresee using more features of this library? I don't like the dependency if it's only for the constants but I think publishing it only for the JVM would be fine as well.

**Comment by hearnadam** [comment]
@fwbrasil I think I just had the dependencies misconfigured...

**Comment by hearnadam** [comment]
@johnhungerford can you try `9.3+110-3ebea0cc-SNAPSHOT`?

**Comment by johnhungerford** [comment]
Now I'm getting the following error:

```
[error] Referring to non-existent method constructor java.util.concurrent.ThreadFactory.<init>()void
[error]   called from constructor java.util.concurrent.ThreadFactoryStub$.<init>()void
[error]   called from kyo.scheduler.util.Threads$.apply(java.lang.String)java.util.concurrent.ThreadFactory
[error]   called from constructor kyo.Timer$.<init>()void
[error]   called from private kyo.Timers$.$init$$$anonfun$1()kyo.Timer
[error]   called from constructor kyo.Timers$.<init>()void
[error]   called from kyo.fibers$package$Fibers$.kyo$fibers$package$Fibers$$$_$transformLoop$8(long,java.lang.Object)java.lang.Object
[error]   called from kyo.fibers$package$Fibers$.sleep(long)java.lang.Object
[error]   called from private zikyoTest.fibersTest.$init$$$anonfun$1$$anonfun$2$$anonfun$2()scala.concurrent.Future
[error]   called from private zikyoTest.fibersTest.$init$$$anonfun$1$$anonfun$2()void
[error]   called from private zikyoTest.fibersTest.$init$$$anonfun$1$$anonfun$adapted$2()java.lang.Object
[error]   called from private zikyoTest.fibersTest.$init$$$anonfun$1()void
[error]   called from private zikyoTest.fibersTest.$init$$$anonfun$adapted$1()java.lang.Object
[error]   called from constructor zikyoTest.fibersTest.<init>()void
[error]   called from static constructor zikyoTest.fibersTest.<stinit>()void
[error]   called from core module analyzer
[error] involving instantiated classes:
[error]   kyo.scheduler.util.Threads$
[error]   kyo.fibers$package$Fibers$
[error] There were linking errors
```

**Pull request merged**
