### PR TITLE
Use `Top.print` to output `Scheduler.Status` to console

### LINKED ISSUE #396: kyo-scheduler: Top output to Console should match JMX
Currently it is just dumping class `.toString`s:

```
Status(10,10,0.0,0,0,4,Vector(WorkerStatus(0,false,,,false,false,0,0,0,0,0,0,0,0,null)
...
```

### PR DESCRIPTION
**Pull request by hearnadam**
Untested, but should resolve #396

### CODE REVIEW

**Comment by fwbrasil** [comment]
Yep! LGTM

**Comment by fwbrasil** [comment]
yeah, no options. Let me try to add a bounty here

/bounty $1

**Comment by hearnadam** [comment]
Ah looks like I will need to open a new PR to claim... /attempt #397

**Comment by hearnadam** [comment]
Let's see if this works: /claim #397

**Comment by fwbrasil** [comment]
hmm no options for payment as well. Let's try the new issue/PR.

**Pull request merged**
